PREFIX segm: <http://fitlayout.github.io/ontology/segmentation.owl#>
PREFIX box: <http://fitlayout.github.io/ontology/render.owl#>
PREFIX r: <http://fitlayout.github.io/resource/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?name ?nbox ?character ?cbox ?episodes ?ebox WHERE {
  ?hbox segm:belongsToChunkSet r:art4 .
  ?hbox segm:text ?header .
  FILTER regex(?header, 'Series Cast ')
  
  ?nbox r:rel-below ?hbox .              # Names are below the header
  ?nbox segm:hasTag r:tag-generic--name .
  ?nbox segm:text ?name .

  ?cbox r:rel-after ?nbox .              # Character names after the header
  ?cbox segm:hasTag r:tag-generic--name .
  ?cbox segm:text ?character .

  ?ebox r:rel-after ?cbox .              # Episodes after the character
  ?ebox segm:hasTag r:tag-generic--credit .
  ?ebox segm:text ?episodes .
}
